### PR TITLE
Fixed bug with multiple validation errors at one field 

### PR DESCRIPTION
**Pull request by xd6d**

### CODE REVIEW

**Review by vetterocki — APPROVED** [review]

**Comment by NikPaukov** [comment]
Why @NotNull instead of @NotBlank on User.password field?
image

**Comment by NikPaukov** [comment]
image
@Schema?

**Comment by NikPaukov** [comment]
image
Where did the diffence come from on UserCreationDto(left) and UserUpdateDto(right)

**Comment by NikPaukov** [comment]
image

not the topic of the pr, but add @Schema here as well please

And maybe copy validation for password & login(if prossible) from UserCreationDto to avoid redundant requests & burden on the server?

**Review by knurff — APPROVED** [review]

**Pull request merged**
